### ISSUE TITLE
@windows not defined

### ISSUE THREAD

**Issue by jabyte** [bicycle1885/Snappy.jl#15]
Hi, I encounter the error below when trying to run cifar10 example.
LoadError: UndefVarError: @windows not defined
while loading /home/user/Mocha.jl-master/examples/cifar10/cifar10.jl, in expression starting on line 3

This is the address of the file I am trying to run when the error occur.
https://github.com/pluskid/Mocha.jl/blob/master/examples/cifar10/cifar10.jl

**Comment by bicycle1885** [comment]
Hi,

Why did you file the issue here?

Your script does not seem to use Snappy.jl and the error message looks unrelated to this package.

**Comment by jabyte** [comment]
I really apologize, something come over my head I wasn't thinking straight. This is not where intended to post it. Sorry once again.
