### ISSUE TITLE
needs update for string.data changes

### ISSUE THREAD

**Issue by stevengj** [bicycle1885/Snappy.jl#4]
After JuliaLang/julia#19449, soon to be merged for Julia 0.6, you will no longer be able to access the raw bytes of a string via `string.data`; instead, do `Vector{UInt8}(string)`.  For example, this affects:

https://github.com/bicycle1885/Snappy.jl/blob/ee2ea60c43364a0b9ca94f605118c2dc10045f12/test/runtests.jl#L21

**Comment by bicycle1885** [comment]
Fixed in #8.
